var lesson1={
  	Monday11a:'География 13',
    Monday11b:'География 13',
  	Monday10a:'Общество 36',
  	Monday9a:'Русск.яз. 36',
  	Monday9b:'Физика 33',
  	Monday8a:'Бел.яз. 21',
  	Monday8b:'Всем. история 22',
  	Monday7a:'Географ. 13',
  	Monday7b:'Бел.яз. 36',
  	Monday6a:'Англ.яз 16/32',
  	Monday6b:'Матем. 34',
    Monday5a:'Матем. 34',
    Monday5b:'Бел.лит. 21',
  	Tuesday11a:'-----',
    Tuesday11b:'-----',
    Tuesday10a:'-----',
  	Tuesday9a:'Физкультура',
  	Tuesday9b:'История Бел. 22',
  	Tuesday8a:'Физкультура',
  	Tuesday8b:'Матем. 34',
  	Tuesday7a:'Ан./Ин.21/25',
  	Tuesday7b:'Химия 32',
  	Tuesday6a:'Физика 33',
  	Tuesday6b:'Географ. 13',
    Tuesday5a:'Русск.яз. 36',
    Tuesday5b:'Русск.яз. 22',
  	Wednesday11a:'-----',
    Wednesday11b:'-----',
    Wednesday10a:'-----',
  	Wednesday9a:'Инф. 25/Англ. 16',
  	Wednesday9b:'Общество 36',
  	Wednesday8a:'Матем. 34',
  	Wednesday8b:'Химия 32',
  	Wednesday7a:'Бел.лит. 35',
  	Wednesday7b:'Физика 33',
  	Wednesday6a:'Физика 33',
  	Wednesday6b:'Русск.яз 36',
    Wednesday5a:'Бел.лит. 21',
    Wednesday5b:'Труд',
  	Thursday11a:'-----',
    Thursday11b:'-----',
    Thursday10a:'-----',
  	Thursday9a:'Труд',
  	Thursday9b:'Англ.яз. 34/35',
  	Thursday8a:'Русск.яз 36',
  	Thursday8b:'Ан./Инф./Ан.16/25/11',
  	Thursday7a:'Матем. 35',
  	Thursday7b:'ЧЗС',
  	Thursday6a:'Матем. 34',
  	Thursday6b:'Биология 13',
    Thursday5a:'Всем. история 21',
    Thursday5b:'Русск.яз. 36',
  	Friday11a:'-----',
    Friday11b:'-----',
    Friday10a:'-----',
  	Friday9a:'Матем. 35',
  	Friday9b:'Бел.лит. 21',
  	Friday8a:'Химия 32',
  	Friday8b:'Физкультура',
  	Friday7a:'Биология 13',
  	Friday7b:'Труд',
  	Friday6a:'Бел.яз. 21',
  	Friday6b:'Англ.яз 36/22',
    Friday5a:'Физкультура',
    Friday5b:'Англ.яз. 16/11/32',
  }
	var lesson2={
  	Monday11a:'География 13',
    Monday11b:'География 13',
    Monday10a:'Общество 36',
  	Monday9a:'Англ.яз. 16/32',
  	Monday9b:'ЧЗС',
  	Monday8a:'Всем. история 22',
  	Monday8b:'Бел.яз. 21',
  	Monday7a:'Бел.яз. 36',
  	Monday7b:'Физкультура',
  	Monday6a:'Матем. 34',
  	Monday6b:'ЧЗС',
    Monday5a:'Бел.яз. 21',
    Monday5b:'Матем. 34',
  	Tuesday11a:'Матем. 34',
  	Tuesday11a:'-----',
    Tuesday11b:'-----',
    Tuesday10a:'-----',
  	Tuesday9b:'Бел.яз. 21',
  	Tuesday8a:'Матем. 34',
  	Tuesday8b:'Физкультура',
  	Tuesday7a:'Матем. 35',
  	Tuesday7b:'Англ./Инф. 16/25',
  	Tuesday6a:'География 13',
  	Tuesday6b:'Физика 33',
    Tuesday5a:'Русск.лит. 36',
    Tuesday5b:'Русск.лит. 22',
  	Wednesday11a:'-----',
    Wednesday11b:'-----',
    Wednesday10a:'-----',
  	Wednesday9a:'Общество  36',
  	Wednesday9b:'Инф. 25/Англ. 16',
  	Wednesday8a:'Химия 32',
  	Wednesday8b:'Матем. 34',
  	Wednesday7a:'Физика 33',
  	Wednesday7b:'Бел.яз. 35',
  	Wednesday6a:'Русск.яз. 36',
  	Wednesday6b:'Англ./Инф. 16/25',
    Wednesday5a:'Труд',
    Wednesday5b:'Матем. 34',
  	Thursday11a:'-----',
    Thursday11b:'-----',
    Thursday10a:'-----',
  	Thursday9a:'Англ.яз. 36/35',
  	Thursday9b:'Труд',
  	Thursday8a:'Англ./Инф. 16/25',
  	Thursday8b:'Русск.яз 36',
  	Thursday7a:'История Бел. 22',
  	Thursday7b:'Русск.яз 32',
  	Thursday6a:'Биология 13',
  	Thursday6b:'Бел.яз. 21',
    Thursday5a:'Матем. 34',
    Thursday5b:'Всем. история 21',
  	Friday11a:'-----',
    Friday11b:'-----',
    Friday10a:'-----',
  	Friday9a:'Бел.лит. 21',
  	Friday9b:'Матем. 35',
  	Friday8a:'Friday8aLesson2',
  	Friday8b:'Химия 32',
  	Friday7a:'Англ.яз. 16/34/13',
  	Friday7b:'Труд',
  	Friday6a:'Англ.яз 36/22',
  	Friday6b:'Бел.яз. 21',
    Friday5a:'Англ.яз. 16/11/32',
    Friday5b:'Физкультура',
  }
  
 var lesson3={
  	Monday11a:'География 13',
    Monday11b:'География 13',
    Monday10a:'Общество 36',
    Monday9a:'ЧЗС',
    Monday9b:'Англ.яз. 16/32',
    Monday8a:'Русск.лит.36',
    Monday8b:'Труд',
    Monday7a:'Русск.яз. 21',
    Monday7b:'Матем. 34',
    Monday6a:'ЧЗС',
    Monday6b:'Англ.яз. 16/32',
    Monday5a:'Бел.лит. 21',
    Monday5b:'Искусство 13',
    Tuesday11a:'-----',
    Tuesday11b:'-----',
    Tuesday10a:'-----',
    Tuesday9a:'История Бел.22',
    Tuesday9b:'Бел. лит. 21',
    Tuesday8a:'Русск.яз. 36',
    Tuesday8b:'Физика 33',
    Tuesday7a:'Химия 32',
    Tuesday7b:'Бел.лит. 35',
    Tuesday6a:'Матем. 34',
    Tuesday6b:'Бел.яз. 21',
    Tuesday5a:'Матем. 34',
    Tuesday5b:'Англ.яз. 16/32/11',
    Wednesday11a:'-----',
    Wednesday11b:'-----',
    Wednesday10a:'-----',
    Wednesday9a:'Англ. 16/Инф. 25',
    Wednesday9b:'География 13',
    Wednesday8a:'Биология 13',
    Wednesday8b:'Бел.лит. 21',
    Wednesday7a:'Биология 35',
    Wednesday7b:'Физкультура',
    Wednesday6a:'Матем. 34',
    Wednesday6b:'Русск.лит. 36',
    Wednesday5a:'Матем. 34',
    Wednesday5b:'Бел.яз. 21',
    Thursday11a:'-----',
    Thursday11b:'-----',
    Thursday10a:'-----',
    Thursday9a:'Матем. 35',
    Thursday9b:'Химия 32',
    Thursday8a:'Инф./Англ. 25/16',
    Thursday8b:'Матем. 34',
    Thursday7a:'Русск.яз 36',
    Thursday7b:'Матем. 35',
    Thursday6a:'История Бел.22',
    Thursday6b:'Бел.лит. 21',
    Thursday5a:'Бел.яз. 21',
    Thursday5b:'Матем. 34',
    Friday11a:'-----',
    Friday11b:'-----',
    Friday10a:'-----',
    Friday9a:'Биология 13',
    Friday9b:'Биология 13',
    Friday8a:'Матем. 34',
    Friday8b:'Англ.яз 16/21/35',
    Friday7a:'Физика 33',
    Friday7b:'Матем. 22',
    Friday6a:'Физкультура',
    Friday6b:'Русск.лит. 36',
    Friday5a:'Матем. 34',
    Friday5b:'Русск.яз. 22',
 }
  
var  lesson4={
  	Monday11a:'География 13',
    Monday11b:'География 13',
    Monday10a:'Общество 36',
    Monday9a:'Черчение 35',
    Monday9b:'Русск.яз. 36',
    Monday8a:'Англ.яз. 16/32',
    Monday8b:'Труд',
    Monday7a:'Матем. 35',
    Monday7b:'География 34',
    Monday6a:'Русск.яз. 36',
    Monday6b:'Всем.история 22',
    Monday5a:'Искусство 13',
    Monday5b:'Англ.яз. 16/34/32',
    Tuesday11a:'-----',
    Tuesday11b:'-----',
    Tuesday10a:'-----',
    Tuesday9a:'Бел.яз. 21',
    Tuesday9b:'Физкультура',
    Tuesday8a:'Русск.лит. 36',
    Tuesday8b:'Географ. 13',
    Tuesday7a:'Всем. история 22',
    Tuesday7b:'Матем. 34',
    Tuesday6a:'Труд',
    Tuesday6b:'Бел.лит. 21',
    Tuesday5a:'Англ.яз. 16/13/11',
    Tuesday5b:'Матем. 34',
    Wednesday11a:'-----',
    Wednesday11b:'-----',
    Wednesday10a:'-----',
    Wednesday9a:'Физика 3',
    Wednesday9b:'Англ. 16/Инф. 2',
    Wednesday8a:'Бел.лит. 2',
    Wednesday8b:'Биология 1',
    Wednesday7a:'Химия 3',
    Wednesday7b:'Бел.лит. 3',
    Wednesday6a:'Русск.лит. 3',
    Wednesday6b:'Матем. 3',
    Wednesday5a:'Чел. и мир 22',
    Wednesday5b:'Бел.лит. 21',
    Thursday11a:'-----',
    Thursday11b:'-----',
    Thursday10a:'-----',
    Thursday9a:'Химия 32',
    Thursday9b:'Матем. 35',
    Thursday8a:'Матем. 34',
    Thursday8b:'Географ. 32',
    Thursday7a:'Англ.яз 16/11',
    Thursday7b:'Русск. лит.36',
    Thursday6a:'Бел.яз. 21',
    Thursday6b:'Матем. 35',
    Thursday5a:'ЧЗС',
    Thursday5b:'Бел. яз. 21',
    Friday11a:'-----',
    Friday11b:'-----',
    Friday10a:'-----',
    Friday9a:'Биология13',
    Friday9b:'Бел.яз.21',
    Friday8a:'Англ.яз 1621',
    Friday8b:'Матем. 34',
    Friday7a:'Матем 35',
    Friday7b:'Физика 33',
    Friday6a:'Матем. 22',
    Friday6b:'Русск.яз. 36',
    Friday5a:'Русск.лит. 36',
    Friday5b:'Матем. 34',
  }
  
var  lesson5={
  	Monday11a:'География 13',
    Monday11b:'География 13',
    Monday10a:'Общество 36',
    Monday9a:'Всем. история 2',
    Monday9b:'Черчение 3',
    Monday8a:'Тру',
    Monday8b:'Англ.яз. 16/32/3',
    Monday7a:'Физкультура',
    Monday7b:'Русск.яз. 21',
    Monday6a:'Всем. история 22',
    Monday6b:'Русск.яз. 36',
    Monday5a:'Англ.яз. 16/34/32',
    Monday5b:'Бел.яз. 21',
    Tuesday11a:'-----',
    Tuesday11b:'-----',
    Tuesday10a:'-----',
    Tuesday9a:'Биология 13',
    Tuesday9b:'Матем. 35',
    Tuesday8a:'Физика 33',
    Tuesday8b:'Русск.яз. 36',
    Tuesday7a:'Бел.лит. 35',
    Tuesday7b:'Инф./Ан. 25/16',
    Tuesday6a:'Бел.яз. 21',
    Tuesday6b:'Матем. 34',
    Tuesday5a:'Физкультура',
    Tuesday5b:'Всем. история 34',
    Wednesday11a:'-----',
    Wednesday11b:'-----',
    Wednesday10a:'-----',
    Wednesday9a:'Матем. 35',
    Wednesday9b:'Физика 33',
    Wednesday8a:'Бел.яз. 21',
    Wednesday8b:'История Бел.22',
    Wednesday7a:'Физкультура',
    Wednesday7b:'Биология 35',
    Wednesday6a:'Инф./Англ. 25/16',
    Wednesday6b:'Физкультура',
    Wednesday5a:'Бел.яз. 21',
    Wednesday5b:'Чел. и мир 22',
    Thursday11a:'-----',
    Thursday11b:'-----',
    Thursday10a:'-----',
    Thursday9a:'Русск.яз. 22',
    Thursday9b:'Русск.лит. 36',
    Thursday8a:'Географ. 32',
    Thursday8b:'ЧЗС',
    Thursday7a:'ЧЗС',
    Thursday7b:'Англ.яз 16/11',
    Thursday6a:'Бел.лит. 21',
    Thursday6b:'История Бел. 22',
    Thursday5a:'Русск.лит. 35',
    Thursday5b:'ЧЗС',
    Friday11a:'-----',
    Friday11b:'-----',
    Friday10a:'-----',
    Friday9a:'Физкультура',
    Friday9b:'Химия 32',
    Friday8a:'Физика 32',
    Friday8b:'Биология 13',
    Friday7a:'Труд',
    Friday7b:'Биология 35',
    Friday6a:'Русск.яз. 36',
    Friday6b:'Матем. 22',
    Friday5a:'Русск.яз. 36',
    Friday5b:'Русск.лит. 22',
  }
  
var  lesson6={
  	Monday11a:'География 13',
    Monday11b:'География 13',
    Monday10a:'Общество 36',
    Monday9a:'Физика 33',
    Monday9b:'Всем. история 22',
    Monday8a:'Труд',
    Monday8b:'Русск.лит.36',
    Monday7a:'-----',
    Monday7b:'-----',
    Monday6a:'-----',
    Monday6b:'-----',
    Monday5a:'-----',
    Monday5b:'-----',
    Tuesday11a:'-----',
    Tuesday11b:'-----',
    Tuesday10a:'-----',
    Tuesday9a:'Бел.лит. 36',
    Tuesday9b:'Биология 13',
    Tuesday8a:'Географ. 34',
    Tuesday8b:'Русск.лит. 36',
    Tuesday7a:'------/Инф./Ан. 25/16',
    Tuesday7b:'Всем. история 22',
    Tuesday6a:'Бел.лит. 21',
    Tuesday6b:'Труд',
    Tuesday5a:'Всем.история 34',
    Tuesday5b:'Физкультура',
    Wednesday11a:'-----',
    Wednesday11b:'-----',
    Wednesday10a:'-----',
    Wednesday9a:'География 13',
    Wednesday9b:'Матем. 35',
    Wednesday8a:'История Бел.22',
    Wednesday8b:'Бел.яз. 21',
    Wednesday7a:'Бел.яз. 35',
    Wednesday7b:'Химия 32',
    Wednesday6a:'Физкультура',
    Wednesday6b:'Инф./Англ. 25/16',
    Wednesday5a:'-----',
    Wednesday5b:'-----',
    Thursday11a:'-----',
    Thursday11b:'-----',
    Thursday10a:'-----',
    Thursday9a:'Русск.лит. 22',
    Thursday9b:'Русск.яз. 36',
    Thursday8a:'ЧЗС',
    Thursday8b:'-----',
    Thursday7a:'Русск.лит. 36',
    Thursday7b:'История Бел.22',
    Thursday6a:'-----',
    Thursday6b:'-----',
    Thursday5a:'-----',
    Thursday5b:'-----',
    Friday11a:'-----',
    Friday11b:'-----',
    Friday10a:'-----',
    Friday9a:'Химия 32',
    Friday9b:'Физкультура',
    Friday8a:'Биология 13',
    Friday8b:'Физика 32',
    Friday7a:'Труд',
    Friday7b:'Англ.яз. 16/34',
    Friday6a:'Русск.лит. 36',
    Friday6b:'Физкультура',
    Friday5a:'-----',
    Friday5b:'-----',
  }
  var  lessonNo={
  	Monday11a:'-----',
  	Monday11b:'-----',
  	Monday10a:'-----',
  	Monday9a:'-----',
  	Monday9b:'-----',
  	Monday8a:'-----',
  	Monday8b:'-----',
  	Monday7a:'-----',
  	Monday7b:'-----',
  	Monday6a:'-----',
  	Monday6b:'-----',
    Monday5a:'-----',
    Monday5b:'-----',
  	Tuesday11a:'-----',
  	Tuesday11b:'-----',
  	Tuesday10a:'-----',
  	Tuesday9a:'-----',
  	Tuesday9b:'-----',
  	Tuesday8a:'-----',
  	Tuesday8b:'-----',
  	Tuesday7a:'-----',
  	Tuesday7b:'-----',
  	Tuesday6a:'-----',
  	Tuesday6b:'-----',
    Tuesday5a:'-----',
    Tuesday5b:'-----',
  	Wednesday11a:'-----',
  	Wednesday11b:'-----',
  	Wednesday10a:'-----',
  	Wednesday9a:'-----',
  	Wednesday9b:'-----',
  	Wednesday8a:'-----',
  	Wednesday8b:'-----',
  	Wednesday7a:'-----',
  	Wednesday7b:'-----',
  	Wednesday6a:'-----',
  	Wednesday6b:'-----',
    Wednesday5a:'-----',
    Wednesday5b:'-----',
  	Thursday11a:'-----',
  	Thursday11b:'-----',
  	Thursday10a:'-----',
  	Thursday9a:'-----',
  	Thursday9b:'-----',
  	Thursday8a:'-----',
  	Thursday8b:'-----',
  	Thursday7a:'-----',
  	Thursday7b:'-----',
  	Thursday6a:'-----',
  	Thursday6b:'-----',
    Thursday5a:'-----',
    Thursday5b:'-----',
  	Friday11a:'-----',
  	Friday11b:'-----',
  	Friday10a:'-----',
  	Friday9a:'-----',
  	Friday9b:'-----',
  	Friday8a:'-----',
  	Friday8b:'-----',
  	Friday7a:'-----',
  	Friday7b:'-----',
  	Friday6a:'-----',
  	Friday6b:'-----',
    Friday5a:'-----',
    Friday5b:'-----'


  }